FROM node:20.17.0-alpine

WORKDIR /app

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

ARG VITE_GOOGLE_MAPS_API_KEY
ENV VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}

ARG VITE_GEOREF_API_URL
ENV VITE_GEOREF_API_URL=${VITE_GEOREF_API_URL}

ARG VITE_IMGUR_API_URL
ENV VITE_IMGUR_API_URL=${VITE_IMGUR_API_URL}

ARG VITE_IMGUR_CLIENT_ID
ENV VITE_IMGUR_CLIENT_ID=${VITE_IMGUR_CLIENT_ID}

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]