// provincias.ts
export const provincias = [
  { id: 'caba', nombre: 'Ciudad Autónoma de Buenos Aires' },
  { id: 'caba-z', nombre: 'Ciudad Autónoma de Buenos Aires' },
  { id: 'buenos-aires', nombre: 'Buenos Aires' },
  { id: 'catamarca', nombre: 'Catamarca' },
  { id: 'chaco', nombre: 'Chaco' },
  { id: 'chubut', nombre: 'Chubut' },
  { id: 'cordoba', nombre: 'Córdoba' },
  { id: 'corrientes', nombre: 'Corrientes' },
  { id: 'entre-rios', nombre: 'Entre Ríos' },
  { id: 'formosa', nombre: 'Formosa' },
  { id: 'jujuy', nombre: 'Jujuy' },
  { id: 'la-pampa', nombre: 'La Pampa' },
  { id: 'la-rioja', nombre: 'La Rioja' },
  { id: 'mendoza', nombre: 'Mendoza' },
  { id: 'misiones', nombre: 'Misiones' },
  { id: 'neuquen', nombre: 'Neuquén' },
  { id: 'rio-negro', nombre: 'Río Negro' },
  { id: 'salta', nombre: 'Salta' },
  { id: 'san-juan', nombre: 'San Juan' },
  { id: 'san-luis', nombre: 'San Luis' },
  { id: 'santa-cruz', nombre: 'Santa Cruz' },
  { id: 'santa-fe', nombre: 'Santa Fe' },
  { id: 'santiago-del-estero', nombre: 'Santiago del Estero' },
  { id: 'tierra-del-fuego', nombre: 'Tierra del Fuego' },
  { id: 'tucuman', nombre: 'Tucumán' },
];
